#!/bin/bash
echo '.bashrc sourced'
if [ -f ~/.bashrc.original ]; then
    source ~/.bashrc.original
fi

for f in ~/.bashrc-*; do
	if [ -f "$f" ]; then
		source $f;
	fi
done

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
